# Site settings
title: XGA.io
description: Unique PvP and PvE servers for everyone
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xga.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: XGA.io
user_description: Unique servers for almost everyone. Join our Discord for the latest news and to share any suggestions. <br />All of our servers begin with [XGA] in the title.
user_title: Public gaming servers for everyone
discord: https://discord.gg/yBrxFdxNBV
twitter_username: xga_io

# Google-analytics
google-analytics:
  id: "G-BYC781DWLR"

exclude: ['package.json', 'src' , 'node_modules']
